### ISSUE TITLE
not adding to path

### ISSUE THREAD

**Issue by hightechstl** [arismelachroinos/lscript#133]
I've used this tool in the past, and I have to say I love it, but here recently, I have run into the issue where on a new install, it is not adding to PATH like it should. It installs, and I can go to /bin/lscript or /lscript/ and run it by using ./l  but it's not adding to ~/.bashrc so I can only launch it if I am in the directory

**Comment by Mikewins1** [comment]
same issue.  and also some not installing at all.  Like wifiphisher here

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wifiphisher==1.4' distribution was not found and is required by the application
Press any key to go back...

**Comment by Ehrgeiz84** [comment]
In Kali Linux path variable l is already in use. If you like to use the shortcut you have to add it manually to your bashrc and comment out the existing alias of "l"
